# Generated by Django 6.0.7 on 2026-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_flatpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='available_from',
            field=models.DateField(default='2026-08-01'),
            preserve_default=False,
        ),
    ]
