# Generated by Django 6.0.7 on 2026-07-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_flatpost_available_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='flatpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flat_listings/'),
        ),
    ]
