# Generated by Django 6.0.7 on 2026-07-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_flatpost_image_url_flatpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpost',
            name='balconies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flatpost',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flatpost',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flatpost',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
