# Generated by Django 6.0.7 on 2026-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_flatpost_balconies_flatpost_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpost',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
