from django.urls import path, include
from rest_framework.routers import DefaultRouter
from accounts.views import CurrentUserView, RegisterView, FlatPostViewSet
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Initialize the router and register the FlatPost ViewSet
router = DefaultRouter()
router.register(r'flat-posts', FlatPostViewSet, basename='flatpost')

urlpatterns = [
    # JWT Authentication Endpoints
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # Registration Endpoint
    path('register/', RegisterView.as_view(), name='register'),
    
    # Include all ViewSet endpoints generated by the router
    # This automatically sets up routes for GET, POST, PUT, DELETE under /api/flat-posts/
    path('', include(router.urls)),
    path('me/', CurrentUserView.as_view(), name='current_user'),
]